name: CI

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: ${{ matrix.name }}
    runs-on: ubuntu-24.04
    env:
      MIX_ENV: test
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Latest Elixir and OTP
            elixir: "> 0"
            otp: "> 0"
            version_type: loose
            lint: true
            coverage: true

          - name: Minimum Elixir and OTP
            elixir: "1.15.0"
            otp: "25.3.2"
            version_type: strict
    steps:
      - name: Check out this repository
        uses: actions/checkout@v7

      - name: Install Erlang/OTP and Elixir
        id: setup-beam
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}
          version-type: ${{ matrix.version_type }}
          hexpm-mirrors: |
            https://builds.hex.pm
            https://cdn.jsdelivr.net/hex

      - name: Cache Mix dependencies
        uses: actions/cache@v6
        with:
          path: |
            deps
            _build
          key: |
            ${{ runner.os }}-mix-${{ steps.setup-beam.outputs.elixir-version }}-${{ steps.setup-beam.outputs.otp-version }}-${{ hashFiles('mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{ steps.setup-beam.outputs.elixir-version }}-${{ steps.setup-beam.outputs.otp-version }}-

      - name: Fetch Mix dependencies (and check mix.lock)
        run: mix deps.get --check-locked

      - name: Check for formatted files
        run: mix format --check-formatted
        if: ${{ matrix.lint }}

      - name: Check for unused dependencies
        run: mix deps.unlock --check-unused
        if: ${{ matrix.lint }}

      - name: Compile Mix dependencies
        run: mix deps.compile

      - name: Check for compilation warnings
        run: mix compile --warnings-as-errors
        if: ${{ matrix.lint }}

      - run: mix test
        if: ${{ !matrix.coverage }}

      - run: mix coveralls.github
        if: ${{ matrix.coverage }}
